### PR TITLE
Dev harness style fixes

### PR DESCRIPTION
**Pull request by Nking92**
Makes the dev harness more consistent with the Jupyter notebook. Also fixes an alignment issue with the Venn diagram.

Here's a preview of what it looks like:

image

Github issue: https://github.com/microsoft/BackwardCompatibilityML/issues/50

### CODE REVIEW

**Review by ilmarinen — APPROVED** [review]
@Nking92 +1

**Review by jlema — CHANGES_REQUESTED** [review]
Looks good overall. The images on the error instances table seem to be missing - is this expected? 
image

**Comment by Nking92** [comment]
> Looks good overall. The images on the error instances table seem to be missing - is this expected?

I added the code to load that in the latest commit. It should work now.

**Review by jlema — APPROVED** [review]
Looks great!

**Review by nushib — APPROVED** [review]

**Review by ilmarinen — APPROVED** [review]

**Pull request merged**
