### PR TITLE
Display error counts as well as percentages within the Venn diagram

### PR DESCRIPTION
**Pull request by ilmarinen**
1. This PR mainly adds the functionality needed to display the error counts in the Venn diagram, together with their percentages.

2. I also fixed one of the example notebooks with an error that Juan found see "examples/bcbinary_cross_entropy.ipynb"

3. I fixed a bug which Nick found where the `model_accuracy` function was not being passed the device type and so would result in an error if the tensors were on the GPU.

### CODE REVIEW

**Review by Nking92 — APPROVED** [review]
Looks good to me.

**Review by jlema — CHANGES_REQUESTED** [review]
When running **bcbinary_cross_entropy**, I am getting **NameError: name 'batch_size_train' is not defined**

This error happens on this line:

_for i in range((batch_size_train - 1), len(training_set), batch_size_train):_

Full stack trace below:

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-11-f4cb5d64ef9e> in <module>
      1 train_loader = []
      2 prev = 0
----> 3 for i in range((batch_size_train - 1), len(training_set), batch_size_train):
      4     training_data = list(map(lambda r: r[0], training_set[prev:i]))
      5     training_labels = list(map(lambda r: r[1], training_set[prev:i]))

NameError: name 'batch_size_train' is not defined

**Comment by jlema** [comment]
Besides the small fix above, the Venn updates look good.

**Comment by ilmarinen** [comment]
@jlema Thanks. Fixed it.

**Review by jlema — APPROVED** [review]

**Review by nushib — APPROVED** [review]

**Pull request merged**
