### PR TITLE
Fix the issue with training on the UCI Adult dataset, by dropping the "fnlwgt" column which was biasing the training

### LINKED ISSUE #116: training using the Adult UCI dataset settles on the most common label 100% of the time

### PR DESCRIPTION
**Pull request by ilmarinen**
I was able to determine that the issue was caused by the "fnlwgt" column, which was being used as a continuous variable, and had very large values.

A simple solution I settled on was to just drop this column. After doing this things immediately improved.

Another solution would be to normalize it. But will stick with the simpler solution for now.

### CODE REVIEW

**Review by nking-1 — APPROVED** [review]
Very cool. Both notebooks ran without any issues, and I got a much nicer graph after doing a sweep.

**Review by jlema — APPROVED** [review]
Also consider removing education and relationship.

**Review by jlema — CHANGES_REQUESTED** [review]
bcbinary_cross_entropy also uses the UCI Adult Data Set. Please apply the same fix to this notebook.

**Comment by ilmarinen** [comment]
> bcbinary_cross_entropy also uses the UCI Adult Data Set. Please apply the same fix to this notebook.

Thanks for catching this. Fixed.

**Review by jlema — APPROVED** [review]

**Review by nushib — APPROVED** [review]
Thanks Xavier!

**Pull request merged**
